### ISSUE TITLE
Consider switching to WebGL 1

### ISSUE THREAD

**Issue by dogfuntom** [verymoko/aerial-lift#3]
WebGL 2 is not compatible with Safari browser. This means it's not compatible with any browser on iOS.
The question is, are we fine without tools that exist only in WebGL 2 (e.g. HDR, PBR).

**Comment by verymoko** [comment]
[Отличия WebGL 1 от 2](https://docs.unity3d.com/Manual/webgl-graphics.html)

**Comment by verymoko** [comment]
[Такой стиль](https://github.com/verymoko/aerial-lift/projects/1#card-65181990) ок на WebGL 1

**Comment by verymoko** [comment]
Перешли
