### ISSUE TITLE
Fix FPS bottleneck on mobile

### ISSUE THREAD

**Issue by dogfuntom** [verymoko/aerial-lift#5]
Plan A
---

Use Profiler. However, it's not clear if Profiler Auto-Connect can work in local network (instead of localhost). It's very possible that it cannot.

Plan B
---

- Use Profiler where it works: in desktop browser, in the editor itself.
- Do the best practices: https://docs.unity3d.com/Manual/webgl-performance.html

Plan C
---

Profile „manually“ (write code that uses Profile API and prints the results on screen or into console log).

**Comment by verymoko** [comment]
expo.genclub.club has the same low FPS. Tested on Huawei P30 Lite M with MS Xbox gamepad

**Comment by verymoko** [comment]
[Graphy is the ultimate and easy to use FPS counter, stats monitor and debugger for your project.](https://assetstore.unity.com/packages/tools/gui/graphy-ultimate-fps-counter-stats-monitor-debugger-105778)

**Comment by dogfuntom** [comment]
# New plan
- [ ] Do some other issue (to return to this issue with fresh mind).
- [x] Try "almost disabling" physic and Graphy (both can be tried in one build).
Physics frequency 0.5 Hz: 3 FPS on Android
- [ ] If experiment is negative, forget about mobile WebGL, do either Android/iOS only or also desktop WebGL 2.

**Comment by verymoko** [comment]
Graphy said on Android: _Window: 2880 ×1800 @ 60 Hz [288 dpi]_, but my phone resolution is 1080 ×1920.

I tried `<meta name="viewport" content="width=device-width, initial-scale=1">` in HTML → head — didn't work.

**Comment by verymoko** [comment]
Uncommented `devicePixelRatio: 1` in HTML → script. _Window: 2880 ×1800 @ 60 Hz [288 dpi]_ changed to _960 × 600 @ 60 Hz [96 dpi]_, increased up to 30 FPS (average 24)
